/** ISO 3166-1 alpha-2 to country name + flag emoji */
const COUNTRIES: Record<string, { name: string; flag: string }> = {
  AF: { name: "Afghanistan", flag: "\u{1F1E6}\u{1F1EB}" },
  AL: { name: "Albania", flag: "\u{1F1E6}\u{1F1F1}" },
  DZ: { name: "Algeria", flag: "\u{1F1E9}\u{1F1FF}" },
  AD: { name: "Andorra", flag: "\u{1F1E6}\u{1F1E9}" },
  AO: { name: "Angola", flag: "\u{1F1E6}\u{1F1F4}" },
  AG: { name: "Antigua and Barbuda", flag: "\u{1F1E6}\u{1F1EC}" },
  AR: { name: "Argentina", flag: "\u{1F1E6}\u{1F1F7}" },
  AM: { name: "Armenia", flag: "\u{1F1E6}\u{1F1F2}" },
  AU: { name: "Australia", flag: "\u{1F1E6}\u{1F1FA}" },
  AT: { name: "Austria", flag: "\u{1F1E6}\u{1F1F9}" },
  AZ: { name: "Azerbaijan", flag: "\u{1F1E6}\u{1F1FF}" },
  BS: { name: "Bahamas", flag: "\u{1F1E7}\u{1F1F8}" },
  BH: { name: "Bahrain", flag: "\u{1F1E7}\u{1F1ED}" },
  BD: { name: "Bangladesh", flag: "\u{1F1E7}\u{1F1E9}" },
  BB: { name: "Barbados", flag: "\u{1F1E7}\u{1F1E7}" },
  BY: { name: "Belarus", flag: "\u{1F1E7}\u{1F1FE}" },
  BE: { name: "Belgium", flag: "\u{1F1E7}\u{1F1EA}" },
  BZ: { name: "Belize", flag: "\u{1F1E7}\u{1F1FF}" },
  BJ: { name: "Benin", flag: "\u{1F1E7}\u{1F1EF}" },
  BT: { name: "Bhutan", flag: "\u{1F1E7}\u{1F1F9}" },
  BO: { name: "Bolivia", flag: "\u{1F1E7}\u{1F1F4}" },
  BA: { name: "Bosnia and Herzegovina", flag: "\u{1F1E7}\u{1F1E6}" },
  BW: { name: "Botswana", flag: "\u{1F1E7}\u{1F1FC}" },
  BR: { name: "Brazil", flag: "\u{1F1E7}\u{1F1F7}" },
  BN: { name: "Brunei", flag: "\u{1F1E7}\u{1F1F3}" },
  BG: { name: "Bulgaria", flag: "\u{1F1E7}\u{1F1EC}" },
  BF: { name: "Burkina Faso", flag: "\u{1F1E7}\u{1F1EB}" },
  BI: { name: "Burundi", flag: "\u{1F1E7}\u{1F1EE}" },
  CV: { name: "Cabo Verde", flag: "\u{1F1E8}\u{1F1FB}" },
  KH: { name: "Cambodia", flag: "\u{1F1F0}\u{1F1ED}" },
  CM: { name: "Cameroon", flag: "\u{1F1E8}\u{1F1F2}" },
  CA: { name: "Canada", flag: "\u{1F1E8}\u{1F1E6}" },
  CF: { name: "Central African Republic", flag: "\u{1F1E8}\u{1F1EB}" },
  TD: { name: "Chad", flag: "\u{1F1F9}\u{1F1E9}" },
  CL: { name: "Chile", flag: "\u{1F1E8}\u{1F1F1}" },
  CN: { name: "China", flag: "\u{1F1E8}\u{1F1F3}" },
  CO: { name: "Colombia", flag: "\u{1F1E8}\u{1F1F4}" },
  KM: { name: "Comoros", flag: "\u{1F1F0}\u{1F1F2}" },
  CG: { name: "Congo", flag: "\u{1F1E8}\u{1F1EC}" },
  CD: { name: "DR Congo", flag: "\u{1F1E8}\u{1F1E9}" },
  CR: { name: "Costa Rica", flag: "\u{1F1E8}\u{1F1F7}" },
  CI: { name: "Ivory Coast", flag: "\u{1F1E8}\u{1F1EE}" },
  HR: { name: "Croatia", flag: "\u{1F1ED}\u{1F1F7}" },
  CU: { name: "Cuba", flag: "\u{1F1E8}\u{1F1FA}" },
  CY: { name: "Cyprus", flag: "\u{1F1E8}\u{1F1FE}" },
  CZ: { name: "Czechia", flag: "\u{1F1E8}\u{1F1FF}" },
  DK: { name: "Denmark", flag: "\u{1F1E9}\u{1F1F0}" },
  DJ: { name: "Djibouti", flag: "\u{1F1E9}\u{1F1EF}" },
  DM: { name: "Dominica", flag: "\u{1F1E9}\u{1F1F2}" },
  DO: { name: "Dominican Republic", flag: "\u{1F1E9}\u{1F1F4}" },
  EC: { name: "Ecuador", flag: "\u{1F1EA}\u{1F1E8}" },
  EG: { name: "Egypt", flag: "\u{1F1EA}\u{1F1EC}" },
  SV: { name: "El Salvador", flag: "\u{1F1F8}\u{1F1FB}" },
  GQ: { name: "Equatorial Guinea", flag: "\u{1F1EC}\u{1F1F6}" },
  ER: { name: "Eritrea", flag: "\u{1F1EA}\u{1F1F7}" },
  EE: { name: "Estonia", flag: "\u{1F1EA}\u{1F1EA}" },
  SZ: { name: "Eswatini", flag: "\u{1F1F8}\u{1F1FF}" },
  ET: { name: "Ethiopia", flag: "\u{1F1EA}\u{1F1F9}" },
  FJ: { name: "Fiji", flag: "\u{1F1EB}\u{1F1EF}" },
  FI: { name: "Finland", flag: "\u{1F1EB}\u{1F1EE}" },
  FR: { name: "France", flag: "\u{1F1EB}\u{1F1F7}" },
  GA: { name: "Gabon", flag: "\u{1F1EC}\u{1F1E6}" },
  GM: { name: "Gambia", flag: "\u{1F1EC}\u{1F1F2}" },
  GE: { name: "Georgia", flag: "\u{1F1EC}\u{1F1EA}" },
  DE: { name: "Germany", flag: "\u{1F1E9}\u{1F1EA}" },
  GH: { name: "Ghana", flag: "\u{1F1EC}\u{1F1ED}" },
  GR: { name: "Greece", flag: "\u{1F1EC}\u{1F1F7}" },
  GD: { name: "Grenada", flag: "\u{1F1EC}\u{1F1E9}" },
  GT: { name: "Guatemala", flag: "\u{1F1EC}\u{1F1F9}" },
  GN: { name: "Guinea", flag: "\u{1F1EC}\u{1F1F3}" },
  GW: { name: "Guinea-Bissau", flag: "\u{1F1EC}\u{1F1FC}" },
  GY: { name: "Guyana", flag: "\u{1F1EC}\u{1F1FE}" },
  HT: { name: "Haiti", flag: "\u{1F1ED}\u{1F1F9}" },
  HN: { name: "Honduras", flag: "\u{1F1ED}\u{1F1F3}" },
  HU: { name: "Hungary", flag: "\u{1F1ED}\u{1F1FA}" },
  IS: { name: "Iceland", flag: "\u{1F1EE}\u{1F1F8}" },
  IN: { name: "India", flag: "\u{1F1EE}\u{1F1F3}" },
  ID: { name: "Indonesia", flag: "\u{1F1EE}\u{1F1E9}" },
  IR: { name: "Iran", flag: "\u{1F1EE}\u{1F1F7}" },
  IQ: { name: "Iraq", flag: "\u{1F1EE}\u{1F1F6}" },
  IE: { name: "Ireland", flag: "\u{1F1EE}\u{1F1EA}" },
  IL: { name: "Israel", flag: "\u{1F1EE}\u{1F1F1}" },
  IT: { name: "Italy", flag: "\u{1F1EE}\u{1F1F9}" },
  JM: { name: "Jamaica", flag: "\u{1F1EF}\u{1F1F2}" },
  JP: { name: "Japan", flag: "\u{1F1EF}\u{1F1F5}" },
  JO: { name: "Jordan", flag: "\u{1F1EF}\u{1F1F4}" },
  KZ: { name: "Kazakhstan", flag: "\u{1F1F0}\u{1F1FF}" },
  KE: { name: "Kenya", flag: "\u{1F1F0}\u{1F1EA}" },
  KI: { name: "Kiribati", flag: "\u{1F1F0}\u{1F1EE}" },
  KP: { name: "North Korea", flag: "\u{1F1F0}\u{1F1F5}" },
  KR: { name: "South Korea", flag: "\u{1F1F0}\u{1F1F7}" },
  KW: { name: "Kuwait", flag: "\u{1F1F0}\u{1F1FC}" },
  KG: { name: "Kyrgyzstan", flag: "\u{1F1F0}\u{1F1EC}" },
  LA: { name: "Laos", flag: "\u{1F1F1}\u{1F1E6}" },
  LV: { name: "Latvia", flag: "\u{1F1F1}\u{1F1FB}" },
  LB: { name: "Lebanon", flag: "\u{1F1F1}\u{1F1E7}" },
  LS: { name: "Lesotho", flag: "\u{1F1F1}\u{1F1F8}" },
  LR: { name: "Liberia", flag: "\u{1F1F1}\u{1F1F7}" },
  LY: { name: "Libya", flag: "\u{1F1F1}\u{1F1FE}" },
  LI: { name: "Liechtenstein", flag: "\u{1F1F1}\u{1F1EE}" },
  LT: { name: "Lithuania", flag: "\u{1F1F1}\u{1F1F9}" },
  LU: { name: "Luxembourg", flag: "\u{1F1F1}\u{1F1FA}" },
  MG: { name: "Madagascar", flag: "\u{1F1F2}\u{1F1EC}" },
  MW: { name: "Malawi", flag: "\u{1F1F2}\u{1F1FC}" },
  MY: { name: "Malaysia", flag: "\u{1F1F2}\u{1F1FE}" },
  MV: { name: "Maldives", flag: "\u{1F1F2}\u{1F1FB}" },
  ML: { name: "Mali", flag: "\u{1F1F2}\u{1F1F1}" },
  MT: { name: "Malta", flag: "\u{1F1F2}\u{1F1F9}" },
  MH: { name: "Marshall Islands", flag: "\u{1F1F2}\u{1F1ED}" },
  MR: { name: "Mauritania", flag: "\u{1F1F2}\u{1F1F7}" },
  MU: { name: "Mauritius", flag: "\u{1F1F2}\u{1F1FA}" },
  MX: { name: "Mexico", flag: "\u{1F1F2}\u{1F1FD}" },
  FM: { name: "Micronesia", flag: "\u{1F1EB}\u{1F1F2}" },
  MD: { name: "Moldova", flag: "\u{1F1F2}\u{1F1E9}" },
  MC: { name: "Monaco", flag: "\u{1F1F2}\u{1F1E8}" },
  MN: { name: "Mongolia", flag: "\u{1F1F2}\u{1F1F3}" },
  ME: { name: "Montenegro", flag: "\u{1F1F2}\u{1F1EA}" },
  MA: { name: "Morocco", flag: "\u{1F1F2}\u{1F1E6}" },
  MZ: { name: "Mozambique", flag: "\u{1F1F2}\u{1F1FF}" },
  MM: { name: "Myanmar", flag: "\u{1F1F2}\u{1F1F2}" },
  NA: { name: "Namibia", flag: "\u{1F1F3}\u{1F1E6}" },
  NR: { name: "Nauru", flag: "\u{1F1F3}\u{1F1F7}" },
  NP: { name: "Nepal", flag: "\u{1F1F3}\u{1F1F5}" },
  NL: { name: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}" },
  NZ: { name: "New Zealand", flag: "\u{1F1F3}\u{1F1FF}" },
  NI: { name: "Nicaragua", flag: "\u{1F1F3}\u{1F1EE}" },
  NE: { name: "Niger", flag: "\u{1F1F3}\u{1F1EA}" },
  NG: { name: "Nigeria", flag: "\u{1F1F3}\u{1F1EC}" },
  MK: { name: "North Macedonia", flag: "\u{1F1F2}\u{1F1F0}" },
  NO: { name: "Norway", flag: "\u{1F1F3}\u{1F1F4}" },
  OM: { name: "Oman", flag: "\u{1F1F4}\u{1F1F2}" },
  PK: { name: "Pakistan", flag: "\u{1F1F5}\u{1F1F0}" },
  PW: { name: "Palau", flag: "\u{1F1F5}\u{1F1FC}" },
  PS: { name: "Palestine", flag: "\u{1F1F5}\u{1F1F8}" },
  PA: { name: "Panama", flag: "\u{1F1F5}\u{1F1E6}" },
  PG: { name: "Papua New Guinea", flag: "\u{1F1F5}\u{1F1EC}" },
  PY: { name: "Paraguay", flag: "\u{1F1F5}\u{1F1FE}" },
  PE: { name: "Peru", flag: "\u{1F1F5}\u{1F1EA}" },
  PH: { name: "Philippines", flag: "\u{1F1F5}\u{1F1ED}" },
  PL: { name: "Poland", flag: "\u{1F1F5}\u{1F1F1}" },
  PT: { name: "Portugal", flag: "\u{1F1F5}\u{1F1F9}" },
  QA: { name: "Qatar", flag: "\u{1F1F6}\u{1F1E6}" },
  RO: { name: "Romania", flag: "\u{1F1F7}\u{1F1F4}" },
  RU: { name: "Russia", flag: "\u{1F1F7}\u{1F1FA}" },
  RW: { name: "Rwanda", flag: "\u{1F1F7}\u{1F1FC}" },
  KN: { name: "Saint Kitts and Nevis", flag: "\u{1F1F0}\u{1F1F3}" },
  LC: { name: "Saint Lucia", flag: "\u{1F1F1}\u{1F1E8}" },
  VC: { name: "Saint Vincent", flag: "\u{1F1FB}\u{1F1E8}" },
  WS: { name: "Samoa", flag: "\u{1F1FC}\u{1F1F8}" },
  SM: { name: "San Marino", flag: "\u{1F1F8}\u{1F1F2}" },
  ST: { name: "Sao Tome and Principe", flag: "\u{1F1F8}\u{1F1F9}" },
  SA: { name: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}" },
  SN: { name: "Senegal", flag: "\u{1F1F8}\u{1F1F3}" },
  RS: { name: "Serbia", flag: "\u{1F1F7}\u{1F1F8}" },
  SC: { name: "Seychelles", flag: "\u{1F1F8}\u{1F1E8}" },
  SL: { name: "Sierra Leone", flag: "\u{1F1F8}\u{1F1F1}" },
  SG: { name: "Singapore", flag: "\u{1F1F8}\u{1F1EC}" },
  SK: { name: "Slovakia", flag: "\u{1F1F8}\u{1F1F0}" },
  SI: { name: "Slovenia", flag: "\u{1F1F8}\u{1F1EE}" },
  SB: { name: "Solomon Islands", flag: "\u{1F1F8}\u{1F1E7}" },
  SO: { name: "Somalia", flag: "\u{1F1F8}\u{1F1F4}" },
  ZA: { name: "South Africa", flag: "\u{1F1FF}\u{1F1E6}" },
  SS: { name: "South Sudan", flag: "\u{1F1F8}\u{1F1F8}" },
  ES: { name: "Spain", flag: "\u{1F1EA}\u{1F1F8}" },
  LK: { name: "Sri Lanka", flag: "\u{1F1F1}\u{1F1F0}" },
  SD: { name: "Sudan", flag: "\u{1F1F8}\u{1F1E9}" },
  SR: { name: "Suriname", flag: "\u{1F1F8}\u{1F1F7}" },
  SE: { name: "Sweden", flag: "\u{1F1F8}\u{1F1EA}" },
  CH: { name: "Switzerland", flag: "\u{1F1E8}\u{1F1ED}" },
  SY: { name: "Syria", flag: "\u{1F1F8}\u{1F1FE}" },
  TW: { name: "Taiwan", flag: "\u{1F1F9}\u{1F1FC}" },
  TJ: { name: "Tajikistan", flag: "\u{1F1F9}\u{1F1EF}" },
  TZ: { name: "Tanzania", flag: "\u{1F1F9}\u{1F1FF}" },
  TH: { name: "Thailand", flag: "\u{1F1F9}\u{1F1ED}" },
  TL: { name: "Timor-Leste", flag: "\u{1F1F9}\u{1F1F1}" },
  TG: { name: "Togo", flag: "\u{1F1F9}\u{1F1EC}" },
  TO: { name: "Tonga", flag: "\u{1F1F9}\u{1F1F4}" },
  TT: { name: "Trinidad and Tobago", flag: "\u{1F1F9}\u{1F1F9}" },
  TN: { name: "Tunisia", flag: "\u{1F1F9}\u{1F1F3}" },
  TR: { name: "Turkey", flag: "\u{1F1F9}\u{1F1F7}" },
  TM: { name: "Turkmenistan", flag: "\u{1F1F9}\u{1F1F2}" },
  TV: { name: "Tuvalu", flag: "\u{1F1F9}\u{1F1FB}" },
  UG: { name: "Uganda", flag: "\u{1F1FA}\u{1F1EC}" },
  UA: { name: "Ukraine", flag: "\u{1F1FA}\u{1F1E6}" },
  AE: { name: "UAE", flag: "\u{1F1E6}\u{1F1EA}" },
  GB: { name: "United Kingdom", flag: "\u{1F1EC}\u{1F1E7}" },
  US: { name: "United States", flag: "\u{1F1FA}\u{1F1F8}" },
  UY: { name: "Uruguay", flag: "\u{1F1FA}\u{1F1FE}" },
  UZ: { name: "Uzbekistan", flag: "\u{1F1FA}\u{1F1FF}" },
  VU: { name: "Vanuatu", flag: "\u{1F1FB}\u{1F1FA}" },
  VA: { name: "Vatican City", flag: "\u{1F1FB}\u{1F1E6}" },
  VE: { name: "Venezuela", flag: "\u{1F1FB}\u{1F1EA}" },
  VN: { name: "Vietnam", flag: "\u{1F1FB}\u{1F1F3}" },
  YE: { name: "Yemen", flag: "\u{1F1FE}\u{1F1EA}" },
  ZM: { name: "Zambia", flag: "\u{1F1FF}\u{1F1F2}" },
  ZW: { name: "Zimbabwe", flag: "\u{1F1FF}\u{1F1FC}" },
  XK: { name: "Kosovo", flag: "\u{1F1FD}\u{1F1F0}" },
};

export function getCountryName(code: string): string {
  return COUNTRIES[code.toUpperCase()]?.name ?? code;
}

export function getCountryFlag(code: string): string {
  return COUNTRIES[code.toUpperCase()]?.flag ?? "";
}

export function formatCountryCodes(codes: string[]): string {
  return codes
    .map((code) => getCountryName(code))
    .join(", ");
}
